// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LyMgma0Y7pov_OfKka4Rqe0ls0MYo4Y',
    appId: '1:510284051462:web:03264d523758c180523f87',
    messagingSenderId: '510284051462',
    projectId: 'chatify-faad3',
    authDomain: 'chatify-faad3.firebaseapp.com',
    storageBucket: 'chatify-faad3.appspot.com',
    measurementId: 'G-WQFFJXMGZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIddmx-oJ8RoZVqPDhLhet-ICG8YuIDLs',
    appId: '1:510284051462:android:83a520e2fb308376523f87',
    messagingSenderId: '510284051462',
    projectId: 'chatify-faad3',
    storageBucket: 'chatify-faad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtkB0Q9EUQ4YI7EhynCYlKKJ_0-XgHdw',
    appId: '1:510284051462:ios:fee52ce43af054ae523f87',
    messagingSenderId: '510284051462',
    projectId: 'chatify-faad3',
    storageBucket: 'chatify-faad3.appspot.com',
    iosBundleId: 'com.example.accentChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNtkB0Q9EUQ4YI7EhynCYlKKJ_0-XgHdw',
    appId: '1:510284051462:ios:5df89665a4287521523f87',
    messagingSenderId: '510284051462',
    projectId: 'chatify-faad3',
    storageBucket: 'chatify-faad3.appspot.com',
    iosBundleId: 'com.example.accentChat.RunnerTests',
  );
}
